"""Canonical sample slide per component — the art shown in a pptx slide layout.

GENERATED by scripts/build_prototypes.py. Do not edit by hand.

Each entry is the raw IR dict for one slide, lifted from that component's example
specimen. `prototype_deck()` re-themes them with the caller's palette so the
layouts in Edit Theme match the deck they ship in.
"""
from __future__ import annotations

from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from slidekit.ir.models import DeckIR, Theme
    from slidekit.layout.models import ResolvedDeck

# component key -> raw slide IR
PROTOTYPES: dict[str, dict] = {'title-slide': {'component': 'title-slide', 'title': 'Quarterly Business Review'},
 'icon-text-rows': {'component': 'icon-text-rows',
                    'title': 'What Drives Us',
                    'rows': [{'icon': 'star',
                              'heading': 'Excellence',
                              'body': 'High standards in every deliverable we ship.'},
                             {'icon': 'handshake',
                              'heading': 'Integrity',
                              'body': 'Transparent and honest in all we do.'},
                             {'icon': 'lightbulb',
                              'heading': 'Innovation',
                              'body': 'Investing in ideas that shape tomorrow.'}]},
 'stat-callout': {'component': 'stat-callout',
                  'title': 'By the Numbers',
                  'stats': [{'value': '127%', 'label': 'Revenue Target'},
                            {'value': '94%', 'label': 'Retention Rate'},
                            {'value': '48 NPS', 'label': 'Net Promoter'}]},
 'comparison-columns': {'component': 'comparison-columns',
                        'title': 'Side-by-Side Evaluation',
                        'left_title': 'Legacy Platform',
                        'right_title': 'Modern Stack',
                        'left_items': [{'text': 'Deploy time: 4 hours'},
                                       {'text': 'Manual scaling'},
                                       {'text': 'On-premise; high cost'}],
                        'right_items': [{'text': 'Deploy time: 8 min'},
                                        {'text': 'Auto-scales fast'},
                                        {'text': 'Cloud-native; low cost'}]},
 'timeline': {'component': 'timeline',
              'title': 'Key Milestones',
              'events': [{'date': 'Q1',
                          'title': 'Foundation',
                          'description': 'Cloud platform migration done.'},
                         {'date': 'Q2',
                          'title': 'API Launch',
                          'description': 'REST API live with 99.99% SLA.'},
                         {'date': 'Q3',
                          'title': 'AI Beta',
                          'description': 'AI features shipped to 500 partners.'},
                         {'date': 'Q4',
                          'title': 'Scale Out',
                          'description': 'APAC regions live; global coverage.'}]},
 'image-half-bleed': {'component': 'image-half-bleed',
                      'title': 'Built in the Field',
                      'image_side': 'left',
                      'image': {'type': 'image',
                                'path': 'assets/team-photo.jpg',
                                'fit': 'cover',
                                'alt': 'Engineering team at a customer site'},
                      'content': [{'type': 'text',
                                   'content': 'Built with customers, not just for '
                                              'them.'},
                                  {'type': 'text',
                                   'content': '60% faster rollout; 50% fewer '
                                              'tickets.'}]},
 'card-grid': {'component': 'card-grid',
               'title': 'What We Offer',
               'cards': [{'icon': 'analytics',
                          'title': 'Insights',
                          'body': 'Live data and AI analytics.'},
                         {'icon': 'shield',
                          'title': 'Security',
                          'body': 'Zero-trust, SOC 2 ready.'},
                         {'icon': 'bolt',
                          'title': 'Speed',
                          'body': 'Sub-100ms p99 latency.'},
                         {'icon': 'puzzle',
                          'title': 'APIs',
                          'body': '300+ open connectors.'}]},
 'section-divider': {'component': 'section-divider',
                     'number': '01',
                     'title': 'Where We Stand Today'},
 'agenda': {'component': 'agenda',
            'title': 'What We Will Cover',
            'items': ['Performance against targets',
                      'Customer and market signals',
                      'Operational health and risks',
                      'Roadmap for next quarter',
                      'Decisions we need today']},
 'big-number': {'component': 'big-number',
                'value': '3.2M',
                'label': 'Active customers worldwide'},
 'pull-quote': {'component': 'pull-quote',
                'quote': 'We stopped buying tools and started buying outcomes.',
                'attribution': 'VP of Engineering, enterprise customer'},
 'definition': {'component': 'definition',
                'term': 'Net Revenue Retention',
                'definition': 'The percentage of recurring revenue retained from '
                              'existing customers over a period, including expansion '
                              'and after churn.'},
 'question': {'component': 'question',
              'question': 'What would we build if we trusted our customers '
                          'completely?'},
 'bullet-list': {'component': 'bullet-list',
                 'title': 'What Changed This Quarter',
                 'items': ['Activation time dropped by half',
                           'Support tickets fell sharply',
                           'Expansion revenue outpaced new sales']},
 'code': {'component': 'code',
          'title': 'hello.py',
          'chrome': True,
          'code': '# The classic, end to end\n'
                  'def main():\n'
                  '    print("Hello, world!")\n'
                  '\n'
                  'main()\n'
                  '\n'
                  '$ python hello.py\n'
                  'Hello, world!\n'},
 'file-tree': {'component': 'file-tree',
               'title': 'Final folder shape',
               'root': 'simple-eda-project/',
               'entries': [{'name': 'src/', 'depth': 0},
                           {'name': 'simple_eda/', 'depth': 1},
                           {'name': '__init__.py', 'depth': 2},
                           {'name': 'core.py', 'depth': 2},
                           {'name': 'README.md', 'depth': 0},
                           {'name': 'pyproject.toml', 'depth': 0},
                           {'name': 'LICENSE', 'depth': 0}]},
 'numbered-steps': {'component': 'numbered-steps',
                    'title': 'Three Steps to Onboard',
                    'steps': [{'title': 'Connect your data',
                               'body': 'Link a source in minutes with a guided '
                                       'wizard.'},
                              {'title': 'Pick a template',
                               'body': 'Start from a proven layout, then tailor it.'},
                              {'title': 'Share the result',
                               'body': 'Publish to your team and gather feedback '
                                       'fast.'}]},
 'two-panel-list': {'component': 'two-panel-list',
                    'title': 'Onboarding, Reworked',
                    'left': {'title': 'Before',
                             'items': ['Manual account setup',
                                       'Three-day approval wait',
                                       'Email-only support']},
                    'right': {'title': 'After',
                              'items': ['One-click provisioning',
                                        'Same-day approval',
                                        'In-product live chat']}},
 'this-vs-that': {'component': 'this-vs-that',
                  'title': 'Cloud or On-Prem',
                  'left': {'value': '3 wks', 'label': 'Cloud time-to-launch'},
                  'right': {'value': '6 mo', 'label': 'On-prem time-to-launch'}},
 'kpi-grid': {'component': 'kpi-grid',
              'title': 'Key Metrics This Quarter',
              'kpis': [{'value': '98.7%', 'label': 'Uptime'},
                       {'value': '1,240', 'label': 'New accounts'},
                       {'value': '4.6/5', 'label': 'Support rating'},
                       {'value': '$2.1M', 'label': 'Net new revenue'},
                       {'value': '12 days', 'label': 'Avg. time to value'},
                       {'value': '31%', 'label': 'Expansion rate'}]},
 'chart-with-insight': {'component': 'chart-with-insight',
                        'title': 'Monthly Active Teams',
                        'chart': {'type': 'chart',
                                  'chart_type': 'bar',
                                  'labels': ['Jan', 'Feb', 'Mar', 'Apr'],
                                  'series': [{'name': 'Active teams',
                                              'values': [120, 180, 290, 460]}]},
                        'insight': 'Activations nearly quadrupled once self-serve '
                                   'onboarding shipped in February.'},
 'table-slide': {'component': 'table-slide',
                 'title': 'Pricing Tiers',
                 'headers': ['Plan', 'Seats', 'Price'],
                 'rows': [['Starter', 'Up to 5', '$0'],
                          ['Team', 'Up to 50', '$12/seat'],
                          ['Business', 'Up to 250', '$20/seat'],
                          ['Enterprise', 'Unlimited', 'Custom']]},
 'metric-comparison': {'component': 'metric-comparison',
                       'title': 'Performance vs Last Year',
                       'metrics': [{'value': '$8.4M',
                                    'label': 'Annual recurring revenue',
                                    'delta': '+24%'},
                                   {'value': '2.1%',
                                    'label': 'Monthly churn',
                                    'delta': '-0.8 pts'},
                                   {'value': '63',
                                    'label': 'Net promoter score',
                                    'delta': '+11'}]},
 'process-steps': {'component': 'process-steps',
                   'title': 'Onboarding Flow',
                   'steps': [{'label': 'Sign up', 'body': 'Create an account'},
                             {'label': 'Connect', 'body': 'Link your data'},
                             {'label': 'Configure', 'body': 'Pick your metrics'},
                             {'label': 'Launch', 'body': 'Go live in minutes'}]},
 'roadmap': {'component': 'roadmap',
             'title': '2026 Plan',
             'phases': [{'title': 'Q1', 'items': ['Ship API', 'Beta launch']},
                        {'title': 'Q2', 'items': ['Mobile app', 'Integrations']},
                        {'title': 'Q3', 'items': ['Enterprise tier', 'SSO']}]},
 'funnel': {'component': 'funnel',
            'title': 'Sales Pipeline',
            'stages': [{'label': 'Visitors', 'value': '50,000'},
                       {'label': 'Signups', 'value': '8,000'},
                       {'label': 'Trials', 'value': '2,400'},
                       {'label': 'Customers', 'value': '600'}]},
 'nested-circles': {'component': 'nested-circles',
                    'title': 'Job Search Funnel (2021)',
                    'stages': [{'value': '>700', 'label': 'Applications'},
                               {'value': '6', 'label': 'Interviews'},
                               {'value': '1.5', 'label': 'Offers'}]},
 'pyramid': {'component': 'pyramid',
             'title': 'Hierarchy of Needs',
             'layers': [{'label': 'Vision'},
                        {'label': 'Strategy'},
                        {'label': 'Goals'},
                        {'label': 'Tactics'}]},
 'swot': {'component': 'swot',
          'title': 'SWOT Analysis',
          'strengths': ['A strong brand with loyal users'],
          'weaknesses': ['Thin margins and a small team'],
          'opportunities': ['New markets through partnerships'],
          'threats': ['New entrants driving price pressure']},
 'comparison-matrix': {'component': 'comparison-matrix',
                       'title': 'Evaluation Matrix',
                       'options': ['Platform A', 'Platform B', 'Platform C'],
                       'criteria': ['Security', 'Workflow', 'Support'],
                       'cells': [['Strong', 'Medium', 'Strong'],
                                 ['Medium', 'Strong', 'Medium'],
                                 ['Strong', 'Strong', 'Medium']],
                       'highlights': [[0, 0], [2, 0]]}}

# Resolving 30 prototypes means real TTF metric work, and emit_pptx runs across
# every example in the suite — so memoise per (theme, canvas). Keyed by the theme's
# serialized form because Theme is a mutable pydantic model, not hashable.
_CACHE: dict[tuple, "ResolvedDeck"] = {}


def prototype_components() -> list[str]:
    """Component keys that have prototype art, in emit order."""
    return list(PROTOTYPES)


def prototype_deck(theme: "Theme") -> "DeckIR":
    """A deck of one sample slide per component, carrying the given theme."""
    from slidekit.ir.models import DeckIR

    return DeckIR.model_validate(
        {
            "version": 1,
            "theme": theme.model_dump(),
            # Page numbers are slide chrome, not layout chrome — a layout must not
            # bake in a page number.
            "page_numbers": {"enabled": False},
            "slides": [dict(s) for s in PROTOTYPES.values()],
        }
    )


def resolved_prototypes(theme: "Theme") -> "ResolvedDeck":
    """Resolve the prototype deck, memoised per theme."""
    from slidekit.layout import resolve

    key = (repr(sorted(theme.model_dump().items())),)
    hit = _CACHE.get(key)
    if hit is None:
        hit = resolve(prototype_deck(theme))
        _CACHE[key] = hit
    return hit
