#!/usr/bin/env python3
"""Generate the *Layout feedback* GitHub issue form from the catalog registry.

The form's Layout dropdown must list exactly the 40 components, so it is GENERATED from
`slidekit.catalog.registry.catalog()` rather than hand-typed — when a component is
added/removed the form regenerates and a test (tests/test_feedback) fails if the
committed file drifts. The form is what the operator fills on their phone (it renders as
a native form in the GitHub mobile app); the feedback-intake workflow parses the
submitted issue into FEEDBACK.yaml.

Usage:
  python scripts/build_feedback_form.py            # (re)write the issue form
  python scripts/build_feedback_form.py --check     # non-zero exit if stale
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from slidekit.catalog.registry import catalog  # noqa: E402

FORM = ROOT / ".github" / "ISSUE_TEMPLATE" / "layout-feedback.yml"


def render() -> str:
    cat = catalog()
    options = "\n".join(f"        - {name}" for name in sorted(cat))
    return f"""\
# Generated by scripts/build_feedback_form.py from src/slidekit/catalog/registry.py.
# Do not hand-edit: the Layout dropdown must mirror the catalog (a test enforces sync).
name: Layout feedback
description: Comment on a specific slide layout
title: "[feedback] "
labels: ["feedback"]
body:
  - type: markdown
    attributes:
      value: |
        Leave a comment on one slide **layout**. To see the layouts, open the latest
        combined preview PDF in `examples/pdf/combined/` (it renders in the GitHub mobile
        app), then pick the layout's name below. The nightly routine reads `open` feedback,
        queues it on the board, and marks it `done`.
  - type: dropdown
    id: component
    attributes:
      label: Layout
      description: The component this feedback is about.
      options:
{options}
    validations:
      required: true
  - type: textarea
    id: comment
    attributes:
      label: Your comment
      description: What works, what doesn't, and what you'd change.
      placeholder: e.g. the hero value sits too low on the canvas; lift it to the optical centre.
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How strongly you feel about it (optional).
      options:
        - low
        - med
        - high
      default: 1
    validations:
      required: false
"""


def main(argv: list[str]) -> int:
    check_only = "--check" in argv
    out = render()
    if check_only:
        current = FORM.read_text(encoding="utf-8") if FORM.exists() else ""
        if current != out:
            print(
                "layout-feedback.yml is out of sync with the catalog — run "
                "`python scripts/build_feedback_form.py`",
                file=sys.stderr,
            )
            return 1
        print("layout-feedback.yml in sync with the catalog.")
        return 0
    FORM.parent.mkdir(parents=True, exist_ok=True)
    FORM.write_text(out, encoding="utf-8")
    print(f"wrote {FORM.relative_to(ROOT)} ({len(catalog())} layouts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
