#!/usr/bin/env python3
"""Generate web/data/decks.json — one geometry-driven HTML preview per slide, per deck.

The feedback website's *deck-review* page shows a whole deck slide-by-slide so the operator
can comment on each slide. Exactly like scripts/build_web_previews.py (which produces ONE
preview per layout component for the layout gallery), this renders through the real pipeline
(`load` → `resolve`) and reuses the geometry-driven HTML emitter — no screenshots — so every
slide preview is faithful to the same math that feeds the .pptx/.pdf.

Scope: the multi-slide *showcase* decks under examples/ (any deck whose stem is NOT the
`NN_component` single-component specimen pattern used by the layout gallery). Each slide
carries its component and a short caption (its headline field) so the reviewer knows what
they are looking at without a rasterised thumbnail.

Run `python scripts/build_web_decks.py` to regenerate, or `--check` to verify the committed
JSON is in sync (used by a test, mirroring build_web_previews / build_examples_index).
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from slidekit.ir import load  # noqa: E402
from slidekit.layout import resolve  # noqa: E402

# Reuse the exact fragment renderer the layout gallery uses (same geometry → HTML).
sys.path.insert(0, str(ROOT / "scripts"))
from build_web_previews import _slide_fragment  # noqa: E402

EXAMPLES = ROOT / "examples"
OUT = ROOT / "web" / "data" / "decks.json"

# Single-component specimens (11_bullet_list.yaml, 44_file_tree.yaml, …) belong to the
# layout gallery; the deck-review page is for real, multi-slide decks only.
_SPECIMEN_RE = re.compile(r"^\d+_")

# Fields to try, in order, for a human-readable one-line caption per slide.
_CAPTION_FIELDS = ("title", "question", "term", "quote", "label", "value", "left_title")


def _caption(slide) -> str:
    """A short headline for a slide, from whichever content field it has."""
    for field in _CAPTION_FIELDS:
        val = getattr(slide, field, None)
        if isinstance(val, str) and val.strip():
            return val.strip()
    return ""


def _deck_title(deck, stem: str) -> str:
    """The deck's display title: its first title-slide's title, else a prettified stem."""
    for s in deck.slides:
        if s.component == "title-slide":
            return s.title
    return stem.replace("-", " ").replace("_", " ").title()


def _showcase_decks() -> list[Path]:
    return [
        f for f in sorted(EXAMPLES.glob("*.yaml"))
        if not _SPECIMEN_RE.match(f.stem)
    ]


def build() -> dict:
    decks: list[dict] = []
    slide_px = None
    for f in _showcase_decks():
        try:
            deck = load(f)
            rd = resolve(deck)
        except Exception as exc:  # pragma: no cover - a broken example is a real failure
            raise SystemExit(f"failed to build {f.name}: {exc}") from exc

        slides = []
        for i, rs in enumerate(rd.slides):
            frag = _slide_fragment(rs, deck)
            if slide_px is None:
                slide_px = {"w": frag["width_px"], "h": frag["height_px"]}
            slides.append({
                "index": i + 1,  # 1-based; matches the `slide` field in FEEDBACK.yaml
                "component": rs.component,
                "caption": _caption(deck.slides[i]),
                **frag,
            })
        decks.append({
            "stem": f.stem,
            "title": _deck_title(deck, f.stem),
            "slide_count": len(slides),
            "slides": slides,
        })

    if not decks:  # pragma: no cover - examples/ always has showcase decks
        raise SystemExit("no showcase decks found under examples/")

    return {
        "note": "GENERATED by scripts/build_web_decks.py — do not hand-edit.",
        "slide_px": slide_px,
        "count": len(decks),
        "decks": decks,
    }


def _serialise(data: dict) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="verify the committed JSON is in sync")
    args = ap.parse_args()

    data = build()
    text = _serialise(data)

    if args.check:
        if not OUT.exists():
            print(f"{OUT.relative_to(ROOT)} is missing — run scripts/build_web_decks.py", file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT.relative_to(ROOT)} is out of date — run scripts/build_web_decks.py", file=sys.stderr)
            return 1
        total = sum(d["slide_count"] for d in data["decks"])
        print(f"{OUT.relative_to(ROOT)} is in sync ({data['count']} decks, {total} slides).")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    total = sum(d["slide_count"] for d in data["decks"])
    print(f"wrote {OUT.relative_to(ROOT)} ({data['count']} decks, {total} slides).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
