"""Regenerate src/slidekit/emit/prototypes.py from the example specimens.

Every pptx slide layout needs representative art. Rather than hand-authoring 30
nested slot structures (and letting them drift from the real models), we lift one
canonical slide per component straight out of the example specimens — decks that
the suite already proves parse, resolve, and lint clean.

The slide's own deck theme is deliberately dropped: prototypes are re-themed with
the caller's palette at emit time, so layout art matches the deck it ships in.

Run after adding or restyling a component:

    python scripts/build_prototypes.py
"""
from __future__ import annotations

import glob
import pprint
import typing
from pathlib import Path

import yaml

from slidekit.ir.models import Slide

ROOT = Path(__file__).resolve().parent.parent
EXAMPLES = ROOT / "examples"
TARGET = ROOT / "src" / "slidekit" / "emit" / "prototypes.py"

_HEADER = '''"""Canonical sample slide per component — the art shown in a pptx slide layout.

GENERATED by scripts/build_prototypes.py. Do not edit by hand.

Each entry is the raw IR dict for one slide, lifted from that component's example
specimen. `prototype_deck()` re-themes them with the caller's palette so the
layouts in Edit Theme match the deck they ship in.
"""
from __future__ import annotations

from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from slidekit.ir.models import DeckIR, Theme
    from slidekit.layout.models import ResolvedDeck

# component key -> raw slide IR
PROTOTYPES: dict[str, dict] = '''

_FOOTER = '''

# Resolving 30 prototypes means real TTF metric work, and emit_pptx runs across
# every example in the suite — so memoise per (theme, canvas). Keyed by the theme's
# serialized form because Theme is a mutable pydantic model, not hashable.
_CACHE: dict[tuple, "ResolvedDeck"] = {}


def prototype_components() -> list[str]:
    """Component keys that have prototype art, in emit order."""
    return list(PROTOTYPES)


def prototype_deck(theme: "Theme") -> "DeckIR":
    """A deck of one sample slide per component, carrying the given theme."""
    from slidekit.ir.models import DeckIR

    return DeckIR.model_validate(
        {
            "version": 1,
            "theme": theme.model_dump(),
            # Page numbers are slide chrome, not layout chrome — a layout must not
            # bake in a page number.
            "page_numbers": {"enabled": False},
            "slides": [dict(s) for s in PROTOTYPES.values()],
        }
    )


def resolved_prototypes(theme: "Theme") -> "ResolvedDeck":
    """Resolve the prototype deck, memoised per theme."""
    from slidekit.layout import resolve

    key = (repr(sorted(theme.model_dump().items())),)
    hit = _CACHE.get(key)
    if hit is None:
        hit = resolve(prototype_deck(theme))
        _CACHE[key] = hit
    return hit
'''


def collect() -> dict[str, dict]:
    """One slide per component, from the first example that supplies it."""
    models = typing.get_args(typing.get_args(Slide)[0])
    want = [typing.get_args(m.model_fields["component"].annotation)[0] for m in models]

    found: dict[str, dict] = {}
    for path in sorted(glob.glob(str(EXAMPLES / "*.yaml"))):
        deck = yaml.safe_load(path and open(path)) or {}
        for slide in deck.get("slides", []) or []:
            comp = slide.get("component")
            if comp in want and comp not in found:
                found[comp] = slide

    missing = [c for c in want if c not in found]
    if missing:
        raise SystemExit(
            f"No example specimen supplies: {', '.join(missing)}. "
            "Add an example deck for it before regenerating."
        )
    # Emit in model-declaration order so the layout list is stable and meaningful.
    return {c: found[c] for c in want}


def render(protos: dict[str, dict]) -> str:
    body = pprint.pformat(protos, width=88, sort_dicts=False)
    return _HEADER + body + _FOOTER


def main() -> None:
    protos = collect()
    TARGET.write_text(render(protos))
    print(f"Wrote {TARGET.relative_to(ROOT)} — {len(protos)} prototypes")


if __name__ == "__main__":
    main()
