#!/usr/bin/env python3
"""Generate web/data/previews.json — one native-HTML preview per layout component.

The feedback website shows every layout so the operator can mark it good/bad. Rather
than rasterise slides (screenshots — the very thing slidekit exists to avoid), we render
each component's specimen deck through the *real* pipeline (`load` → `resolve`) and reuse
the geometry-driven HTML preview emitter to produce an absolute-positioned fragment. The
website scales those fragments down to thumbnails; they stay faithful to the same math
that feeds the .pptx/.pdf, backgrounds included.

Coverage source: `examples/NN_<component>.yaml` is a canonical one-deck-per-component
specimen set. We prefer single-slide specimens for a component's representative preview
and fall back to the first matching slide in any multi-slide showcase, so all components
in the catalog are covered.

Run `python scripts/build_web_previews.py` to regenerate, or `--check` to verify the
committed JSON is in sync (used by a test, mirroring build_examples_index / render_board).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from slidekit.catalog.registry import catalog  # noqa: E402
from slidekit.emit.html_preview import _node_html  # noqa: E402
from slidekit.ir import load  # noqa: E402
from slidekit.layout import resolve  # noqa: E402

EXAMPLES = ROOT / "examples"
OUT = ROOT / "web" / "data" / "previews.json"


def _slide_fragment(rs, deck) -> dict:
    """Render one resolved slide to an absolute-positioned HTML fragment + geometry."""
    palette = deck.theme.palette
    surface = rs.background or palette.surface
    nodes_html = "\n".join(_node_html(n, palette) for n in rs.nodes + rs.chrome)
    return {
        "width_px": round(rs.canvas_w / (914400 / 96), 2),
        "height_px": round(rs.canvas_h / (914400 / 96), 2),
        "background": surface,
        "nodes_html": nodes_html,
    }


def build() -> dict:
    reg = catalog()
    # Prefer single-slide specimens (clean, dedicated) before multi-slide showcases.
    files = sorted(EXAMPLES.glob("*.yaml"))
    decks: list[tuple[Path, object, object]] = []
    for f in files:
        try:
            deck = load(f)
            rd = resolve(deck)
        except Exception as exc:  # pragma: no cover - a broken example is a real failure
            raise SystemExit(f"failed to build {f.name}: {exc}") from exc
        decks.append((f, deck, rd))
    decks.sort(key=lambda t: (len(t[2].slides), t[0].name))  # specimens first

    captured: dict[str, dict] = {}
    for f, deck, rd in decks:
        for rs in rd.slides:
            comp = rs.component
            if comp in captured or comp not in reg:
                continue
            lo = reg[comp]
            frag = _slide_fragment(rs, deck)
            captured[comp] = {
                "component": comp,
                "family": lo.family,
                "role": lo.role,
                "variant_of": lo.variant_of,
                "differs_by": lo.differs_by,
                "purpose": lo.purpose,
                "use_when": lo.use_when,
                "example": f.name,
                **frag,
            }

    missing = sorted(set(reg) - set(captured))
    if missing:
        raise SystemExit(
            f"no specimen slide found for {len(missing)} component(s): {missing}"
        )

    # Emit in catalog order (stable, matches docs) so diffs stay clean.
    components = [captured[c] for c in reg]
    return {
        "note": "GENERATED by scripts/build_web_previews.py — do not hand-edit.",
        "slide_px": {"w": components[0]["width_px"], "h": components[0]["height_px"]},
        "count": len(components),
        "components": components,
    }


def _serialise(data: dict) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="verify the committed JSON is in sync")
    args = ap.parse_args()

    data = build()
    text = _serialise(data)

    if args.check:
        if not OUT.exists():
            print(f"{OUT.relative_to(ROOT)} is missing — run scripts/build_web_previews.py", file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT.relative_to(ROOT)} is out of date — run scripts/build_web_previews.py", file=sys.stderr)
            return 1
        print(f"{OUT.relative_to(ROOT)} is in sync ({data['count']} components).")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({data['count']} components).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
