"""Guard for the generated web preview data (web/data/previews.json).

Same golden/sync spirit as the examples index and board: previews.json is committed and
generated by scripts/build_web_previews.py, so a test asserts it (a) covers exactly the
catalog's components, (b) carries a renderable fragment per component, and (c) stays in
sync with its generator. This keeps the feedback website from silently drifting out of
step with the layout catalog.
"""
import importlib.util
import json
from pathlib import Path

from slidekit.catalog.registry import catalog

ROOT = Path(__file__).resolve().parent.parent.parent
_SPEC = importlib.util.spec_from_file_location(
    "build_web_previews", ROOT / "scripts" / "build_web_previews.py"
)
bwp = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(bwp)


def test_build_is_deterministic():
    assert bwp._serialise(bwp.build()) == bwp._serialise(bwp.build())


def test_previews_in_sync():
    committed = bwp.OUT.read_text(encoding="utf-8")
    assert committed == bwp._serialise(bwp.build()), (
        "web/data/previews.json is stale — run `python scripts/build_web_previews.py`"
    )


def test_covers_every_component():
    data = json.loads(bwp.OUT.read_text(encoding="utf-8"))
    listed = {c["component"] for c in data["components"]}
    assert listed == set(catalog()), "previews.json must cover exactly the catalog components"
    assert data["count"] == len(catalog())


def test_every_preview_has_a_fragment():
    data = json.loads(bwp.OUT.read_text(encoding="utf-8"))
    for c in data["components"]:
        assert c["nodes_html"].strip(), f"{c['component']} has an empty preview fragment"
        assert c["width_px"] > 0 and c["height_px"] > 0
        assert c["background"].startswith("#"), f"{c['component']} background not a hex colour"
        # Metadata the website relies on for the card header.
        assert c["purpose"] and c["use_when"] and c["family"]
