"""Guard for the generated deck-review data (web/data/decks.json).

Same golden/sync spirit as web/data/previews.json: decks.json is committed and generated by
scripts/build_web_decks.py, so a test asserts it (a) stays in sync with its generator,
(b) is deterministic, (c) covers every multi-slide showcase deck under examples/, and
(d) carries a renderable fragment + 1-based index per slide (the index the FEEDBACK.yaml
`slide` field references). This keeps the deck-review page from silently drifting out of
step with the decks it reviews.
"""
import importlib.util
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
_SPEC = importlib.util.spec_from_file_location(
    "build_web_decks", ROOT / "scripts" / "build_web_decks.py"
)
bwd = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(bwd)

_SPECIMEN_RE = re.compile(r"^\d+_")


def test_build_is_deterministic():
    assert bwd._serialise(bwd.build()) == bwd._serialise(bwd.build())


def test_decks_in_sync():
    committed = bwd.OUT.read_text(encoding="utf-8")
    assert committed == bwd._serialise(bwd.build()), (
        "web/data/decks.json is stale — run `python scripts/build_web_decks.py`"
    )


def test_covers_every_showcase_deck():
    data = json.loads(bwd.OUT.read_text(encoding="utf-8"))
    listed = {d["stem"] for d in data["decks"]}
    expected = {
        f.stem for f in (ROOT / "examples").glob("*.yaml")
        if not _SPECIMEN_RE.match(f.stem)
    }
    assert listed == expected, "decks.json must cover exactly the multi-slide showcase decks"
    assert data["count"] == len(expected)
    # Single-component specimens belong to the layout gallery, not the deck-review page.
    assert not any(_SPECIMEN_RE.match(s) for s in listed)


def test_slides_are_indexed_and_renderable():
    data = json.loads(bwd.OUT.read_text(encoding="utf-8"))
    for deck in data["decks"]:
        assert deck["slide_count"] == len(deck["slides"])
        assert deck["title"]
        for i, s in enumerate(deck["slides"], start=1):
            assert s["index"] == i, f"{deck['stem']}: slide index must be 1-based and contiguous"
            assert s["component"], f"{deck['stem']} #{i}: missing component"
            assert s["nodes_html"].strip(), f"{deck['stem']} #{i}: empty preview fragment"
            assert s["width_px"] > 0 and s["height_px"] > 0
            assert s["background"].startswith("#")
