/* slidekit layout-feedback site.
 *
 * Loads web/data/previews.json (one geometry-driven HTML preview per layout, generated by
 * scripts/build_web_previews.py), renders a scaled thumbnail + good/bad + comment per
 * component, and POSTs the marks to the Netlify submit function. Auth is handled entirely
 * at the edge (a signed cookie set by netlify/edge-functions/auth.js); this page is only
 * served once that cookie is valid, and the same-origin fetch carries it automatically, so
 * there is no token handling here.
 */
(function () {
  "use strict";

  var STAGE_W = 1280; // previews are authored at 1280×720 (16:9 at 96 DPI)
  var state = {};     // component -> { verdict: "good"|"bad"|null, comment, severity }

  var gallery = document.getElementById("gallery");
  var submitBtn = document.getElementById("submit");
  var pendingEl = document.getElementById("pending");
  var countsEl = document.getElementById("counts");

  function esc(s) { var d = document.createElement("div"); d.textContent = s == null ? "" : s; return d.innerHTML; }

  function markedCount() {
    return Object.keys(state).filter(function (k) {
      var s = state[k];
      return s.verdict || (s.comment && s.comment.trim());
    }).length;
  }

  function refreshFooter() {
    var n = markedCount();
    submitBtn.disabled = n === 0;
    pendingEl.textContent = n === 0 ? "No marks yet." : n + " layout" + (n === 1 ? "" : "s") + " marked.";
    var good = 0, bad = 0;
    Object.keys(state).forEach(function (k) {
      if (state[k].verdict === "good") good++;
      else if (state[k].verdict === "bad") bad++;
    });
    countsEl.innerHTML = "<b>" + good + "</b> good · <span class='b-bad'>" + bad + "</span> needs work";
  }

  function scaleStage(stage, preview, w, h) {
    var avail = preview.clientWidth;
    var scale = avail / w;
    stage.style.transform = "scale(" + scale + ")";
    preview.style.height = (h * scale) + "px";
  }

  function makeCard(c) {
    state[c.component] = { verdict: null, comment: "", severity: "med" };

    var card = document.createElement("section");
    card.className = "card";
    card.dataset.component = c.component;

    var role = c.role === "variant" ? ("variant of " + c.variant_of) : c.family;

    card.innerHTML =
      '<div class="card-head">' +
        '<div class="card-title"><h2>' + esc(c.component) + '</h2>' +
        '<span class="tag">' + esc(role) + '</span></div>' +
        '<p class="card-purpose">' + esc(c.purpose) + '</p>' +
        '<p class="card-when">Use when: ' + esc(c.use_when) + '</p>' +
      '</div>' +
      '<div class="preview"><div class="stage" style="width:' + c.width_px + 'px;height:' + c.height_px +
        'px;background:' + esc(c.background) + '">' + c.nodes_html + '</div></div>' +
      '<div class="controls">' +
        '<div class="verdict">' +
          '<button type="button" class="vbtn good" data-v="good">👍 Good</button>' +
          '<button type="button" class="vbtn bad" data-v="bad">👎 Needs work</button>' +
        '</div>' +
        '<textarea class="comment" placeholder="Optional note — what to change…"></textarea>' +
        '<label class="sev">Severity ' +
          '<select><option value="low">low</option><option value="med" selected>med</option>' +
          '<option value="high">high</option></select></label>' +
      '</div>';

    var stage = card.querySelector(".stage");
    var preview = card.querySelector(".preview");
    // Scale once inserted (needs layout width), and on resize/orientation change.
    requestAnimationFrame(function () { scaleStage(stage, preview, c.width_px, c.height_px); });
    window.addEventListener("resize", function () { scaleStage(stage, preview, c.width_px, c.height_px); });

    var vbtns = card.querySelectorAll(".vbtn");
    vbtns.forEach(function (btn) {
      btn.addEventListener("click", function () {
        var v = btn.dataset.v;
        var st = state[c.component];
        st.verdict = st.verdict === v ? null : v; // tap again to clear
        vbtns.forEach(function (b) { b.classList.toggle("on", b.dataset.v === st.verdict); });
        card.classList.toggle("marked-good", st.verdict === "good");
        card.classList.toggle("marked-bad", st.verdict === "bad");
        refreshFooter();
      });
    });
    card.querySelector(".comment").addEventListener("input", function (e) {
      state[c.component].comment = e.target.value;
      refreshFooter();
    });
    card.querySelector(".sev select").addEventListener("change", function (e) {
      state[c.component].severity = e.target.value;
    });

    return card;
  }

  function toast(msg, isErr) {
    var t = document.getElementById("toast");
    t.textContent = msg;
    t.className = "toast show" + (isErr ? " err" : "");
    setTimeout(function () { t.className = "toast" + (isErr ? " err" : ""); }, 3200);
  }

  function collect() {
    // A comment turns an unmarked layout into an implicit "note" verdict so nothing is lost.
    return Object.keys(state).map(function (comp) {
      var s = state[comp];
      var comment = (s.comment || "").trim();
      if (!s.verdict && !comment) return null;
      return { component: comp, verdict: s.verdict || "note", comment: comment, severity: s.severity };
    }).filter(Boolean);
  }

  function submit() {
    var items = collect();
    if (!items.length) return;
    submitBtn.disabled = true;
    submitBtn.textContent = "Submitting…";
    fetch("/.netlify/functions/submit-feedback", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      credentials: "same-origin",
      body: JSON.stringify({ items: items })
    }).then(function (r) {
      return r.json().catch(function () { return {}; }).then(function (body) {
        if (!r.ok) throw new Error(body.error || ("HTTP " + r.status));
        return body;
      });
    }).then(function (body) {
      toast("Saved " + items.length + " mark" + (items.length === 1 ? "" : "s") +
            (body.commit ? " · commit " + String(body.commit).slice(0, 7) : "") + ".");
      // Reset marks after a successful commit.
      document.querySelectorAll(".card").forEach(function (card) {
        card.classList.remove("marked-good", "marked-bad");
        card.querySelectorAll(".vbtn").forEach(function (b) { b.classList.remove("on"); });
        card.querySelector(".comment").value = "";
      });
      Object.keys(state).forEach(function (k) { state[k] = { verdict: null, comment: "", severity: "med" }; });
      refreshFooter();
    }).catch(function (err) {
      toast("Submit failed: " + err.message, true);
    }).finally(function () {
      submitBtn.textContent = "Submit feedback";
      refreshFooter();
    });
  }

  submitBtn.addEventListener("click", submit);

  fetch("/data/previews.json", { credentials: "same-origin" })
    .then(function (r) { if (!r.ok) throw new Error("HTTP " + r.status); return r.json(); })
    .then(function (data) {
      gallery.innerHTML = "";
      gallery.setAttribute("aria-busy", "false");
      data.components.forEach(function (c) { gallery.appendChild(makeCard(c)); });
      refreshFooter();
    })
    .catch(function (err) {
      gallery.innerHTML = '<p class="loading">Could not load layouts: ' + esc(err.message) + '</p>';
    });
})();
